// Program to check odd or even using modulus operator;
//author:Sebak Thapa

#include <stdio.h>
#include <stdbool.h>

int main() {
    int a;
    
//    taking data from user
    printf("Enter a number: ");
    scanf("%d", &a);
    
// checking the condition and displaying result 
	printf("\n\nThe output generated by using modulus operator: \n");
	if(a % 2  == 0){
		printf("%d is even number", a);
	}else{
		printf("%d is odd number", a);
	}
	
	printf("\n\nThe output generated by using bitwise operator: \n");
	if(a & 1  == 0){
		printf("%d is odd number", a);
	}else{
		printf("%d is even number", a);
	}
	
	
	//    running the loop to check for enven or odd
	int i;
	bool iseven=false;
	for(i=0; i<=a;i++){
		iseven = !iseven;
	}
	
//	displaying 
	printf("\n\nThe output generated without using modulus or bitwise operator: \n");
	if(iseven){
		printf("%d is even number", a);
	}else{
		printf("%d is odd number", a);
	}
	
	printf("\n\nThe output generated without using ternary conditional operator: \n");
	 // checking the consdition and displaying result 
	a % 2 == 0 ?  printf("%d is even number", a) : printf("%d is odd number", a);

    return 0;
}
